name: jsbackend CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Out Repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: cd jsbackend && npm install

      - name: Run tests
        run: cd jsbackend && npm test
